# Interface Black list

int_blacklist:
  - pod: 1
    node: 101
    interface: 1/2
    blacklist: no
  - pod: 1
    node: 101
    interface: 1/5
    blacklist: no
  - pod: 1
    node: 102
    interface: 1/2
    blacklist: yes
  - pod: 1
    node: 102
    interface: 1/5
    blacklist: yes

change_ticket: TEST123