---
- name: ACI Playbook
  hosts: aci
  gather_facts: no

  vars:
    aci_user: admin
    aci_pwd: ciscopsdt
    aci_host: sandboxapicdc.cisco.com

  vars_prompt:
    - name: "new_tenant"
      prompt: "Enter New Tenant Name:"
      default: "LAX_Tenant"
      private: no

  tasks:

  - name: Add the New Tenant
    aci_tenant:
      host: "{{ aci_host }}"
      username: "{{ aci_user }}"
      password: "{{ aci_pwd }}"
      validate_certs: no
      tenant: production
      description: Production tenant
      state: present
    delegate_to: localhost

  - name: Query all tenants
    aci_tenant:
      host: "{{ aci_host }}"
      username: "{{ aci_user }}"
      password: "{{ aci_pwd }}"
      validate_certs: no
      use_ssl: yes
      timeout: 90

      state: query
    delegate_to: localhost
    register: all_tenants

  - name: Display RAW APIC Results
    debug:
      var: all_tenants
#      verbosity: 2
