---
###############################################################################
# This interactive playbook queries for information and action and performs
# the selection Tenant action against the DevNet Sandbox APIC
# EXECUTION:
# ansible-playbook -i hosts aci_tenant_prompt.yml
###############################################################################

- name: ACI Playbook to Perform User Prompted Action on Tenant
  hosts: aci
  gather_facts: no

  vars:
    aci_user: admin
    aci_pwd: ciscopsdt
    aci_host: sandboxapicdc.cisco.com

# Prompt for the Tenant Name and Tenant action
  vars_prompt:
    - name: "tenant_name"
      prompt: "Enter Tenant Name"
      default: "LAX_Tenant"
      private: no

    - name: "tenant_state"
      prompt: "Enter Tenant State (absent | present | query)"
      default: "query"
      private: no


  tasks:

# setting a variable with the current date and time to use for the object description
  - name: Set Date
    set_fact: curr_date="{{lookup('pipe','date \"+%Y-%m-%d %H:%M\"')}}"

# Note that the aci_tenant module (and ACI) is idempotent so "add" is actually "add if needed" as is delete
  - name: "Add, Delete, or Query Tenant {{ tenant_name }}"
    aci_tenant:
      host: "{{ aci_host }}"
      username: "{{ aci_user }}"
      password: "{{ aci_pwd }}"
      validate_certs: no
      tenant: "{{ tenant_name }}"
      description: "Tenant {{ tenant_name }} Action {{tenant_state}} on {{ curr_date }}"
      state: "{{ tenant_state }}"
    delegate_to: localhost
    register: tenant_results

  - debug:
      var: tenant_results

  - name: Query all tenants
    aci_tenant:
      host: "{{ aci_host }}"
      username: "{{ aci_user }}"
      password: "{{ aci_pwd }}"
      validate_certs: no
      use_ssl: yes
      timeout: 90

      state: query
    delegate_to: localhost
    register: all_tenants

  - name: Display RAW APIC Results
    debug:
      var: all_tenants
      verbosity: 1

#  - debug:
#      var: "{{ item.fvTenant.attributes.name }}"
#      verbosity: 2
#    with_items:
#      - "{{  all_tenants.current  }}"

  - set_fact:
      tenantlist: "{{ all_tenants.current | map(attribute='fvTenant.attributes.name') | list }}"

  - name: Tenants returned in Query ==>
    debug:
      var: tenantlist



