---
###############################################################################
# This playbook executes a basic Tenant query
###############################################################################
- name: ACI Tenant Query Playbook
  hosts: aci_sandbox
  gather_facts: no


  tasks:

  - name: Query all tenants
    aci_tenant:
      host: sandboxapicdc.cisco.com
      username: admin
      password: ciscopsdt
      validate_certs: no
      use_ssl: yes
      timeout: 90

      state: query
    delegate_to: localhost
    register: all_tenants

  - name: Display RAW APIC Results
    debug:
      var: all_tenants
      verbosity: 2

  - name: Display Item in Returned Dict
    debug:
      var: all_tenants['current']
      verbosity: 2

  - name: Display Specific Values from APIC Results
    debug:
      msg: "Tenant Name: {{ item['fvTenant']['attributes']['name'] }}"
      verbosity: 2
    with_items:
      - "{{ all_tenants['current'] }}"
    no_log: True

  - name: Clean Tenant Listing
    set_fact:
      clean_out: "{{ clean_out|default([]) + [item['fvTenant']['attributes']['name']] }}"
    with_items:
      - "{{ all_tenants['current'] }}"
    no_log: True

  - name: Tenant Listing
    debug:
      msg: "Tenant Name: {{ item }}"
    with_items:
      - "{{ clean_out }}"
    tags: DEBUG