---
###############################################################################
# This playbook executes a GET action on an APIC Controller via the Ansible ACI Rest Module
###############################################################################
- name: ACI Tenant GET Playbook
  hosts: aci_sandbox
  gather_facts: no

  vars:
    aci_user: admin
    aci_pwd: ciscopsdt
    aci_host: sandboxapicdc.cisco.com

  tasks:

  - name: Query
    aci_rest:
      host: "{{ aci_host }}"
      username: "{{ aci_user }}"
      password: "{{ aci_pwd }}"
      validate_certs: no
      method: get
      output_level: normal
      # path: /api/node/class/fvTenant.json
      path: /api/node/mo/uni/infra/attentp-AEP_NAME.json?query-target=self
      # path: /api/node/mo/uni/infra/attentp-default-aep/fltCnts.json?subscription=yes
      # path: /api/node/mo/uni/infra.json?query-target=children&target-subtree-class=infraAttEntityP
    delegate_to: localhost
    register: query_result


  - debug:
      var: query_result

