---
###############################################################################
# This playbook executes actions on an APIC Controller via the Ansible ACI Rest Module
###############################################################################
- name: ACI Backup Export Playbook
  hosts: aci
  gather_facts: no

  vars:
    aci_user: admin
    aci_pwd: ciscopsdt
    aci_host: sandboxapicdc.cisco.com
    rem_name: Prod_SCP_Server_1.1.1.1
    scp_user: aci_backup
    scp_pwd: Cisco123
    scp_ip: 1.1.1.1
    exp_name: Backup Export Policy for SCP


  tasks:

  - name: Create a Remote Location
    aci_rest:
      host: "{{ aci_host }}"
      username: "{{ aci_user }}"
      password: "{{ aci_pwd }}"
      validate_certs: no
      method: post
      path: "/api/node/mo/uni.json"
      content:
        {
          "fileRemotePath": {
            "attributes": {
              "dn": "uni/fabric/path-{{ rem_name }}",
              "remotePort": 22,
              "name": "{{ rem_name }}",
              "descr": "Production SCP Server",
              "protocol": "scp",
              "userName": "{{ scp_user }}",
              "userPasswd": "{{ scp_pwd }}",
              "host": "{{ scp_ip }}"
            },
            "children": []
          }
        }
    delegate_to: localhost



  - name: Create an Export Policy
    aci_rest:
      host: "{{ aci_host }}"
      username: "{{ aci_user }}"
      password: "{{ aci_pwd }}"
      validate_certs: no
      method: post
      path: "/api/node/mo/uni.json"
      content:
        {
          "configExportP": {
              "attributes": {
                  "dn": "uni/fabric/configexp-{{ exp_name }}",
                  "name": "{{ exp_name }}",
                  "descr": "Export Policy for SCP",
                  "adminSt": "triggered",
                   "format": "json",
              },
              "children": [{
                  "configRsExportScheduler": {
                      "attributes": {
                          "tnTrigSchedPName": "EveryEightHours",
                          "status": "created,modified"
                      },
                      "children": []
                  }
              },
              {
                  "configRsRemotePath": {
                      "attributes": {
                          "tnFileRemotePathName": "{{ rem_name }}"
                          "status": "created,modified"
                      },
                      "children": []
                  }
              }]
          }
        }