---
- name: ACI Tenant Query Playbook
  hosts: aci
  gather_facts: no

  vars:
    aci_user: admin
    aci_pwd: ciscopsdt
    aci_host: sandboxapicdc.cisco.com

  tasks:
  - name: Query all tenants task
    aci_tenant:
      host: "{{ aci_host }}"
      username: "{{ aci_user }}"
      password: "{{ aci_pwd }}"
      validate_certs: no
      timeout: 90
      state: query
    delegate_to: localhost
    register: all_tenants


  - set_fact:
      tenantlist: "{{ all_tenants.current | map(attribute='fvTenant.attributes.name') | list }}"

  - name: Tenants returned in Query ==>
    debug:
      var: tenantlist


  - name: with_indexed_items -> loop
    debug:
      msg: "Item Index {{ index }} - {{ item }}"
    loop: "{{ tenantlist }}"
    loop_control:
      index_var: index


  - local_action: copy content="{{ tenantlist | to_nice_yaml }}" dest="./host_vars/{{ inventory_hostname }}-fvTenant.yml"
  - local_action: copy content="{{ tenantlist | to_nice_json }}" dest="./host_vars/{{ inventory_hostname }}-fvTenant.json"

- name: ACI VRF
  hosts: aci
  gather_facts: no

  tasks:
  - debug:
      var: tenantlist

