---
- name: ACI Playbook to Perform User Prompted Action on VRF
  hosts: aci
  gather_facts: no

  vars:
    aci_user: admin
    aci_pwd: ciscopsdt
    aci_host: sandboxapicdc.cisco.com

#  vars_prompt:
#    - name: "vrf_name"
#      prompt: "Enter Tenant Name:"
#      default: "LAX_Tenant"
#      private: no
#
#    - name: "vrf_state"
#      prompt: "Enter Tenant State (absent | present | query:"
#      default: "query"
#      private: no

  tasks:
    - name: Get Tenant List Variables
      include_vars: "./host_vars/{{ inventory_host }}-fvTenant.yml"