---
###############################################################################
# This playbook executes actions on an APIC Controller via the Ansible ACI Rest Module
###############################################################################
- name: ACI Tenant Query Playbook
  hosts: aci
  gather_facts: no


  vars:
    aci_user: admin
    aci_pwd: ciscopsdt
    aci_host: sandboxapicdc.cisco.com
    query_path: '/api/node/class/infraWiNode.json'
    method: 'get'

  tasks:

  - name: "Execute REST Call Action: {{ method | upper }} Query: {{ query_path }} "
    aci_rest:
      host: "{{ aci_host }}"
      username: "{{ aci_user }}"
      password: "{{ aci_pwd }}"
      validate_certs: no
      method: "{{ method }}"
      path: "{{ query_path }}"
    delegate_to: localhost
    register: query_result

  - name: Display RAW APIC Results
    debug:
      var: query_result
#      verbosity: 1
