---
###############################################################################
# This playbook executes actions on an APIC Controller via the Ansible ACI Rest Module
###############################################################################
- name: ACI EPG Query Playbook
  hosts: aci_sandbox
  gather_facts: no


  vars:
    # These variables should be set in a host_var host file
#    aci_user: admin
#    aci_pwd: ciscopsdt
#    aci_host: sandboxapicdc.cisco.com
    epgs:
      - Citrix-EPG
      - SharePoint-EPG
    query_path: '/api/node/mo/uni/tn-GDL-PROD-TN/ap-Citrix-ANP/epg-<EPG VALUE>.json?query-target=children'
    method: 'get'
    ignore_errors: yes

  #

  tasks:

  - name: "Execute REST Call Action: {{ method | upper }} Query: {{ query_path }} "
    aci_rest:
      host: "{{ aci_host }}"
      username: "{{ aci_user }}"
      password: "{{ aci_pwd }}"
      validate_certs: no
      method: "{{ method }}"
      path: "/api/node/mo/uni/tn-GDL-PROD-TN/ap-Citrix-ANP/epg-{{ item }}.json?query-target=children"
    delegate_to: localhost
    with_items: "{{ epgs }}"
    register: query_result

  - name: Display RAW APIC Results
    debug:
      var: query_result

  - name: "Display APIC Results for EPG {{ epgs[0] }}"
    debug:
      msg: "EPG CONSUMED CONTRACTS {{ epgs[0] }} query_result is {{query_result['results'][0]['imdata'] }}"

  - set_fact:
      epg1: "{{ query_result['results'][0]['imdata'] }}"

  - set_fact:
      epg2: "{{ query_result['results'][1]['imdata'] }}"

  - name: "Display EPG {{ epgs[0] }} CONSUMED Contracts"
    debug:
      msg: "EPG {{ epgs[0] }} CONSUMES {{ item['fvRsCons']['attributes']['tnVzBrCPName'] }} "
    with_items: "{{ epg1 }}"
    when: item['fvRsCons'] is defined

  - name: "Display EPG {{ epgs[0] }} PROVIDED Contracts"
    debug:
      msg: "EPG {{ epgs[0] }} PROVIDES {{ item['fvRsProv']['attributes']['tnVzBrCPName'] }} "
    with_items: "{{ epg1 }}"
    when: item['fvRsProv'] is defined


  - name: Query all provider contract to EPG bindings
    aci_epg_to_contract:
      host: "{{ aci_host }}"
      username: "{{ aci_user }}"
      password: "{{ aci_pwd }}"
      validate_certs: no
      contract_type: provider
      state: query
    delegate_to: localhost
    register: query_result

  - name: Display RAW APIC Results of Query all provider contract to EPG bindings
    debug:
      var: query_result

  - name: Query a specific contract to EPG binding
    aci_epg_to_contract:
      host: "{{ aci_host }}"
      username: "{{ aci_user }}"
      password: "{{ aci_pwd }}"
      validate_certs: no
      tenant: GDL-PROD-TN
      ap: Citrix-ANP
      epg: Citrix-EPG
      contract: default
      contract_type: provider
      state: query
    delegate_to: localhost

  - name: Display RAW APIC Results Query a specific contract to EPG binding
    debug:
      var: query_result