---
###############################################################################
# This playbook executes actions on an APIC Controller via the Ansible ACI Rest Module
###############################################################################
- name: ACI EPG Query Playbook
  hosts: local_aci
  gather_facts: no


#  vars:
#    aci_user: admin
#    aci_pwd: ciscopsdt
#    aci_host: sandboxapicdc.cisco.com
#    query_path: '/api/node/mo/uni/tn-GDL-PROD-TN/ap-Citrix-ANP/epg-Citrix-EPG.json?query-target=children'
#    method: 'get'
  vars:
    aci_user: admin
    aci_pwd: cisco123
    aci_host: 10.1.10.111
    epgs:
      - Citrix-EPG
      - SharePoint-EPG
    query_path: '/api/node/mo/uni/tn-GDL-PROD-TN/ap-Citrix-ANP/epg-<EPG VALUE>.json?query-target=children'
    method: 'get'
    ignore_errors: yes

  #

  tasks:

  - name: "Execute REST Call Action: {{ method | upper }} Query: {{ query_path }} "
    aci_rest:
      host: "{{ aci_host }}"
      username: "{{ aci_user }}"
      password: "{{ aci_pwd }}"
      validate_certs: no
      method: "{{ method }}"
      path: "/api/node/mo/uni/tn-GDL-PROD-TN/ap-Citrix-ANP/epg-{{ item }}.json?query-target=children"
    delegate_to: localhost
    with_items: "{{ epgs }}"
    register: query_result

  - name: Display RAW APIC Results
    debug:
      var: query_result

  - name: "Display APIC Results for FIRST EPG"
    debug:
      msg: "EPG CONSUMED CONTRACTS {{ epgs[0] }} query_result is {{query_result['results'][0]['imdata'] }}"

  - set_fact:
      epg1: "{{ query_result['results'][0]['imdata'] }}"

  - set_fact:
      epg2: "{{ query_result['results'][1]['imdata'] }}"

  - name: Display EPG1 Consumed Contracts
    debug:
#      msg: "EPG CONSUMES {{ item['fvRsCons']['attributes']['tnVzBrCPName'] }} "
      msg: "EPG {{ epgs[0] }} CONSUMES {{ item['fvRsCons']['attributes']['tnVzBrCPName'] }} "
#      msg: "EPG CONSUMES {{ item }} "
    with_items: "{{ epg1 }}"
    ignore_errors: yes
    when: item['fvRsCons'] is defined

  - name: "Display EPG1 {{ epgs[0] }} Provided Contracts"
    debug:
#      msg: "EPG CONSUMES {{ item['fvRsCons']['attributes']['tnVzBrCPName'] }} "
      msg: "EPG {{ epgs[0] }} PROVIDES {{ item['fvRsProv']['attributes']['tnVzBrCPName'] }} "
#      msg: "EPG CONSUMES {{ item }} "
    with_items: "{{ epg1 }}"
    ignore_errors: yes
    when: item['fvRsProv'] is defined



#
#  - name: Summary of APIC Cluster Health
#    debug:
#      msg: "APIC: {{ item['infraWiNode']['attributes']['nodeName'] }} Health is {{ item['infraWiNode']['attributes']['health'] }} "
#    with_items: "{{ query_result['imdata'] }}"
#
#  - name: Look for APICs which are NOT FULLY FIT
#    debug:
#      msg: "APIC NOT FULLY FIT: {{ item['infraWiNode']['attributes']['nodeName'] }} Health is {{ item['infraWiNode']['attributes']['health'] }} "
#    with_items: "{{ query_result['imdata'] }}"
#    when: item['infraWiNode']['attributes']['health']  != 'fully-fit'
#
#  - name: Look for APICs which ARE FULLY FIT
#    debug:
#      msg: "APIC FULLY FIT: {{ item['infraWiNode']['attributes']['nodeName'] }} Health is {{ item['infraWiNode']['attributes']['health'] }} "
#    with_items: "{{ query_result['imdata'] }}"
#    when: item['infraWiNode']['attributes']['health']  == 'fully-fit'