---
###############################################################################
# Test Playbook
###############################################################################
- name: ACI Playbook to Perform User Prompted Action on VRF
  hosts: aci
  gather_facts: no

  vars_files:
    - "./host_vars/{{ inventory_host }}-fvTenant.yml"
    - ./host_vars/test.yml

  vars:
    aci_user: admin
    aci_pwd: ciscopsdt
    aci_host: sandboxapicdc.cisco.com

#  vars_prompt:
#    - name: "vrf_name"
#      prompt: "Enter Tenant Name:"
#      default: "LAX_Tenant"
#      private: no
#
#    - name: "vrf_state"
#      prompt: "Enter Tenant State (absent | present | query:"
#      default: "query"
#      private: no

  tasks:

  - name: Display all variables/facts known for a host
    debug:
      var: hostvars[inventory_hostname]
    tags: debug_info

  - name: Print some debug information
    vars:
      msg: |
          Module Variables ("vars"):
          --------------------------------
          {{ vars | to_nice_json }}

          Environment Variables ("environment"):
          --------------------------------
          {{ environment | to_nice_json }}

          GROUP NAMES Variables ("group_names"):
          --------------------------------
          {{ group_names | to_nice_json }}

          GROUPS Variables ("groups"):
          --------------------------------
          {{ groups | to_nice_json }}

          HOST Variables ("hostvars"):
          --------------------------------
          {{ hostvars | to_nice_json }}

    debug:
      msg: "{{ msg.split('\n') }}"
